image_width: 3840
image_height: 2160
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [2365.30187,    0.     , 1985.8571 ,
            0.     , 2362.58847, 1097.7695 ,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.340133, 0.093689, -0.000078, 0.001290, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1703.75208,    0.     , 2040.38019,    0.     ,
            0.     , 2176.27637, 1100.40609,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
