image_width: 3840
image_height: 2160
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [2352.30428,    0.     , 1975.00273,
            0.     , 2348.85144, 1103.08148,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.335911, 0.089398, -0.000012, 0.001493, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1682.78076,    0.     , 2029.17858,    0.     ,
            0.     , 2163.52246, 1106.85155,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
