image_width: 3840
image_height: 2160
camera_name: s2-camera2
camera_matrix:
  rows: 3
  cols: 3
  data: [2337.56344,    0.     , 1986.77997,
            0.     , 2327.36657, 1052.44656,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.340615, 0.093804, -0.003224, 0.001485, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1671.16577,    0.     , 2042.14944,    0.     ,
            0.     , 2135.76392, 1039.74955,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
