image_width: 3840
image_height: 2160
camera_name: s3-camera3
camera_matrix:
  rows: 3
  cols: 3
  data: [2368.41042,    0.     , 1958.62088,
            0.     , 2363.82182,  991.18942,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.336671, 0.086325, 0.000666, 0.001318, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1678.21399,    0.     , 2004.85403,    0.     ,
            0.     , 2175.00146,  975.72315,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
